spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  thymeleaf:
    mode: LEGACYHTML5
    characterEncoding: UTF-8
    cache: false
  jackson:
    serialization:
      write_dates_as_timestamps: false
