spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database: H2
  datasource:
    url: jdbc:h2:/tmp/dijleserver.tmp;AUTO_SERVER=TRUE;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
  thymeleaf:
    mode: LEGACYHTML5
    characterEncoding: UTF-8
    cache: false
  jackson:
    serialization:
      write_dates_as_timestamps: false
      
      
      
