spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    database: H2
  datasource:
    url: jdbc:h2:/tmp/dijleserver.tmp;AUTO_SERVER=TRUE;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
  thymeleaf:
    mode: LEGACYHTML5
    characterEncoding: UTF-8
    cache: false
  jackson:
    serialization:
      write_dates_as_timestamps: false
google:
  api:
    key: AIzaSyBiXXRQ89oU0vrf-5fnCwpEap8LOIPRV50
---
spring:
  jpa:
    hibernate:
      ddl-auto: update
  profiles: production
  thymeleaf:
    prefix: classpath:/templates
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/dijlecontrol_prd_db
    username: dijlecontrol_prd_user
server:
  port: 80
logging:
  path: /var/log/dijle

      
